version: '2'

services:

  nextjs-app:
    image: 192.168.1.151:32000/nextjs-app:1.22.66
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      TEMPORAL_CLI_ADDRESS: temporaltest-frontend-headless:7233
